### ISSUE TITLE
Can you update the sample with the last version of esp_nano_httpd?

### ISSUE THREAD

**Issue by fvpalha** [QB4-dev/esp_nano_httpd_fota#1]
Hi @QB4-dev.

Can you update the sample "esp_nano_httpd_fota" with the last version of "esp_nano_httpd"?

Thank you.

**Comment by fvpalha** [comment]
Hi @QB4-dev.

The sample does not upload files (flash file content) after update the esp_nano_httpd.

**Comment by QB4-dev** [comment]
Hello @fvpalha  
I've updated this example to  latest version of nano httpd.Now should work for you

**Comment by fvpalha** [comment]
Thank you very much, @QB4-dev. 
Congratulations on your great work.

**Comment by fvpalha** [comment]
> Hi @QB4-dev.
> 
> The sample does not upload files (flash file content) after update the esp_nano_httpd.

In my test this resource yet does not work.
The ESP8266 rebooting when click "Upload".

**Comment by QB4-dev** [comment]
@fvpalha  

> In my test this resource yet does not work.
> The ESP8266 rebooting when click "Upload"

That's right, you have found a bug - there was NULL pointer exception when accepted file extension wasn't specified. Now should work properly

**Comment by fvpalha** [comment]
Thank you very much @QB4-dev. 
Now everything works.
