### ISSUE TITLE
Max file size

### ISSUE THREAD

**Issue by fvpalha** [QB4-dev/esp_nano_httpd_fota#2]
Hi @QB4-dev.

How can I increase the limit of file size?

`
file_info_t flash_txt_file = {
	.accept_file_ext = ".txt",
	.accept_cont_type = "text",
	.base_sec = 0x250,
	.max_f_size = 4*SPI_FLASH_SEC_SIZE
};
`

I tried "max_f_size = 8*SPI_FLASH_SEC_SIZE" and after send the file, I received the message:

`500 Internal Error`

Thank you.

**Comment by fvpalha** [comment]
`max_f_size = 5*SPI_FLASH_SEC_SIZE`

This change works!

**Comment by fvpalha** [comment]
`max_f_size = 6*SPI_FLASH_SEC_SIZE`

This change does not work.

**Comment by fvpalha** [comment]
> `max_f_size = 5*SPI_FLASH_SEC_SIZE`
> 
> This change works!

When I sending file with 17 kb and above, it does not work:

`500 Internal Error`

I tried with 16896 bytes and it worked.

**Comment by QB4-dev** [comment]
Hello
The reason why Internal error is returned is that ESP cannot allocate enough RAM memory to prepare and send text from flash if it's more than ~20kB. It happens in this place in function `flash_read_callback`:

```C
flash_buff = (const char *)os_malloc(f_info->max_f_size);
if(flash_buff == NULL)
	return resp_http_error(conn);
```
This function was designed only for example to show that uploaded file content is really in ESP flash memory. 
If you need to read data bigger than free ESP RAM memory you need to do it in smaller chunks. 
Content of your file should have been uploaded to flash correctly. The problem exists if you want to read it all at once. Is it really required in your application?

**Comment by fvpalha** [comment]
Hello.

I'm going to use your example to transfer a new firmware to another device.
Thank you very much for the tips.
